spring.application.name=bfhl-api
server.port=${PORT:8080}

bfhl.user-id=${BFHL_USER_ID:praxx_999}
bfhl.email=${BFHL_EMAIL:prathmesgholap999@gmail.com}
bfhl.roll-number=${BFHL_ROLL_NUMBER:9607779799}
bfhl.async-threshold=${BFHL_ASYNC_THRESHOLD:10000}
